spring:
  application:
    name: bitcoin-client
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
      bindings:
        prices-in-0:
          destination: com.ivanfranchin.bitcoin.api.price
          group: bitcoinClientGroup
        transaction-in-0:
          destination: com.ivanfranchin.bitcoin.api.transaction
          group: bitcoinClientGroup
    function:
      definition: transaction;prices

management:
  endpoints:
    web:
      exposure:
        include: >
          actuator,prometheus,health,env,auditevents,
          caches,configprops,httptrace,info,loggers,
          metrics,mappings,scheduledtasks,logfile
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ClientApp
